name: base
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.8
  - argcomplete=3.1.1
  - argh=0.27.2
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.40
  - biopython=1.81
  - boltons=23.0.0
  - bpipe=0.9.11
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - clustalw=2.1
  - collectl=4.0.4
  - colorama=0.4.6
  - conda=23.3.1
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - coreutils=9.3
  - cryptography=41.0.1
  - curl=8.1.2
  - expat=2.5.0
  - fastool=0.1.4
  - fastp=0.23.4
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gffcompare=0.12.6
  - gffread=0.12.7
  - gffutils=0.11.1
  - gfortran_impl_linux-64=12.2.0
  - giflib=5.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=7.3.0
  - hisat2=2.2.1
  - hmmer=3.3.2
  - htslib=1.17
  - icu=72.1
  - idna=3.4
  - isa-l=2.30.0
  - java-jdk=8.0.92
  - jellyfish=2.2.10
  - jemalloc=4.5.0
  - jsonpatch=1.32
  - jsonpointer=2.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libgomp=13.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsanitizer=12.2.0
  - libsolv=0.7.24
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.11.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - mamba=1.1.0
  - ncbi-vdb=3.0.5
  - ncurses=6.4.20240210
  - nextflow=23.04.1
  - numpy=1.25.0
  - openjdk=11.0.15
  - openssl=3.1.2
  - ossuuid=1.6.2
  - packaging=23.1
  - pandoc=2.19.2
  - pango=1.50.14
  - parafly=r2013_01_21
  - pblat=2.5.1
  - pcre2=10.40
  - perl=5.22.0.1
  - perl-app-cpanminus=1.7043
  - perl-bioperl=1.6.924
  - perl-constant=1.33
  - perl-extutils-makemaker=6.66
  - perl-io-tty=1.12
  - perl-ipc-run=0.94
  - perl-module-runtime=0.014
  - perl-moose=2.1804
  - perl-pathtools=3.40
  - perl-scalar-list-utils=1.45
  - perl-test-warnings=0.021
  - perl-threaded=5.32.1
  - perl-try-tiny=0.24
  - perl-uri=1.71
  - perl-xml-libxml=2.0124
  - perl-xml-namespacesupport=1.11
  - perl-xml-sax=0.99
  - perl-xml-sax-base=1.08
  - perl-yaml=1.24
  - pfam_scan=1.6
  - pip=22.3.1
  - pixman=0.40.0
  - plek=1.2
  - pluggy=1.0.0
  - pthread-stubs=0.4
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyfaidx=0.7.2.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.10
  - python_abi=3.10
  - pyvcf3=1.0.3
  - r=4.3
  - r-admisc=0.33
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.0
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-broom=1.0.5
  - r-bslib=0.5.0
  - r-cachem=1.0.8
  - r-callr=3.7.3
  - r-cellranger=1.1.0
  - r-class=7.3_22
  - r-cli=3.6.1
  - r-clipr=0.8.0
  - r-cluster=2.1.4
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-conflicted=1.2.0
  - r-cpp11=0.4.5
  - r-crayon=1.5.2
  - r-curl=5.0.1
  - r-data.table=1.14.8
  - r-dbi=1.1.3
  - r-dbplyr=2.3.3
  - r-digest=0.6.33
  - r-dplyr=1.1.2
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.21
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreign=0.8_84
  - r-fs=1.6.3
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.4.2
  - r-ggpolypath=0.2.0
  - r-glue=1.6.2
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gtable=0.3.3
  - r-haven=2.5.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.5
  - r-httr=1.4.6
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.7
  - r-kernsmooth=2.23_21
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-lattice=0.21_8
  - r-lifecycle=1.0.3
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.5_4.1
  - r-memoise=2.0.1
  - r-mgcv=1.8_42
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_162
  - r-nnet=7.3_19
  - r-openssl=2.0.6
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.1.1
  - r-processx=3.8.2
  - r-progress=1.2.2
  - r-ps=1.7.5
  - r-purrr=1.0.1
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.11
  - r-readr=2.1.4
  - r-readxl=1.4.3
  - r-recommended=4.3
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.2
  - r-rlang=1.1.1
  - r-rmarkdown=2.23
  - r-rpart=4.1.19
  - r-rstudioapi=0.15.0
  - r-rvest=1.0.3
  - r-sass=0.4.7
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-spatial=7.3_16
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-survival=3.5_5
  - r-sys=3.4.2
  - r-systemfonts=1.0.4
  - r-textshaping=0.3.6
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.2.0
  - r-tinytex=0.45
  - r-tzdb=0.4.0
  - r-utf8=1.2.3
  - r-uuid=1.1_0
  - r-vctrs=0.6.3
  - r-venn=1.11
  - r-viridislite=0.4.2
  - r-vroom=1.6.3
  - r-withr=2.5.0
  - r-xfun=0.39
  - r-xml2=1.3.5
  - r-yaml=2.3.7
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - samtools=1.6
  - sed=4.8
  - seqtk=1.4
  - setuptools=67.7.2
  - simplejson=3.19.1
  - six=1.16.0
  - slclust=02022010
  - sra-tools=3.0.3
  - stringtie=2.1.7
  - subread=2.0.3
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - toolz=0.12.0
  - tqdm=4.65.0
  - trimmomatic=0.39
  - trinity=2.1.1
  - urllib3=2.0.3
  - wheel=0.40.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - attrs==23.1.0
      - cattrs==23.1.2
      - exceptiongroup==1.1.1
      - future==0.18.3
      - pandas==2.0.2
      - platformdirs==3.6.0
      - pybiomart==0.2.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests-cache==1.0.1
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - url-normalize==1.4.3
