// Path to tools used by the pipeline
bpipe="/opt/data/home/nikhil/anaconda3/bin/bpipe"
hisat2="/opt/data/home/nikhil/anaconda3/bin/hisat2"
stringtie="/opt/data/home/nikhil/anaconda3/bin/stringtie"
gffread="/opt/data/home/nikhil/anaconda3/bin/gffread"
blat="/opt/data/home/nikhil/anaconda3/bin/blat"
pblat="/opt/data/home/nikhil/anaconda3/bin/pblat"
python="/opt/data/home/nikhil/anaconda3/bin/python"
lace="/opt/data/home/nikhil/anaconda3/bin/Lace.py"
gtf2flatgtf="/opt/data/home/nikhil/necklace/tools/bin/gtf2flatgtf"
samtools="/opt/data/home/nikhil/anaconda3/bin/samtools"
Trinity="/opt/data/home/nikhil/anaconda3/bin/Trinity"
bowtie2="/usr/local/bin/bowtie2"
make_blocks="/opt/data/home/nikhil/necklace/tools/bin/make_blocks"
featureCounts="/opt/data/home/nikhil/anaconda3/bin/featureCounts"
chimera_breaker="/opt/data/home/nikhil/necklace/tools/bin/chimera_breaker"
remove_clusters_match="/opt/data/home/nikhil/necklace/tools/bin/remove_clusters_match"
final_cluster="/opt/data/home/nikhil/necklace/tools/bin/final_cluster"

